### ISSUE TITLE
Menu bar does not hide when vullScreen is executed

### ISSUE THREAD

**Issue by Millani** [KabbAmine/vullScreen.vim#2]
I am using your great plugin as an easy way to make Vim (not GVim) start already in full-screen. I simply put the `VullScreen` command with an `autocmd` in the `.vimrc` file.

While it does work perfectly for maximizing the terminal where Vim is launched, it does not to toggle the Menubar off. Would you know of a way to achieve that?

**Comment by KabbAmine** [comment]
Unfortunately, the menu depends of the terminal itself while in gvim, the gui elements can be turned on/off with the vim option `guioptions`.

We may implement a workaround for each terminal if the latter supports a toggling menu command, but it adds too much complexity for nothing and is way beyond the plugin's scope.

I'm closing the issue, but feel free to provide me more informations about your terminal so we may found a solution.

**Comment by Millani** [comment]
> Unfortunately, the menu depends of the terminal itself while in gvim, the gui elements can be turned on/off with the vim option `guioptions`.
> 
> We may implement a workaround for each terminal if the latter supports a toggling menu command, but it adds too much complexity for nothing and is way beyond the plugin's scope.
> 
> I'm closing the issue, but feel free to provide me more informations about your terminal so we may found a solution.

I see your point. Which info exactly do you need from my terminal that would be useful? I am in a Ubuntu 18.04.1 LTS, Releas 18.04, using a xterm-256colors. My terminal does not seem to have a official shortcut for toggling the menu bar on/off.

Thanks!

**Comment by KabbAmine** [comment]
I'm asking because many terminals allow changing their options in realtime, but this is not the case for xterm.

The best option for you is to completely disable the toolbar in your `Xresources` file, AFAIK it should be disabled by default.

**Comment by Millani** [comment]
Ok, that makes sense. Yeap, for now I will do exactly that, I will just disable the toolbar entirely. Later, I might investigate whether one can set a shortcut for toggling the toolbar on the terminal side and then modify your script to send such combination of key presses to the terminal upon activation.

Thanks!
